name: scheduled-test 
on:
  schedule:
    - cron:  '0 22 * * 1-5'    # Every M-F at 10pm
  workflow_dispatch:
    branches:
      - 'main'
jobs:
  run-scheduled-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
          cache: gradle
  run-snapshot-tests:
    uses: ./.github/workflows/tecton-e2e-test.yml
    with:
      client_version: SNAPSHOT
    secrets:
      TECTON_URL: ${{ secrets.TECTON_URL }} 
      TECTON_API_KEY: ${{ secrets.TECTON_API_KEY }}
  run-stable-release-tests:
    uses: ./.github/workflows/tecton-e2e-test.yml
    with:
      client_version: RELEASE
    secrets:
      TECTON_URL: ${{ secrets.TECTON_URL }}
      TECTON_API_KEY: ${{ secrets.TECTON_API_KEY }}
