name: scheduled-test 
on:
  schedule:
    - cron:  '0 22 * * 1-5'    # Every M-F at 10pm
  workflow_dispatch:
    branches:
      - 'main'
jobs:
  run-scheduled-tests:
    runs-on: ubuntu-latest
    needs: java-gradle-build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
          cache: gradle
      - name: Run Tests for Latest Snapshot 
        uses: ./.github/workflows/tecton-e2e-test.yml
        with:
          client_version: latest.integration
      - name: Run Tests for Latest Public Release
        uses: ./.github/workflows/tecton-e2e-test.yml
        with:
          client_version: latest.release
