name: tecton-e2e-test 
on:
  workflow_call:
    inputs:
      client_version:
        required: true
        type: string
    secrets:
      TECTON_URL:
        description: 'Tecton Service URL'
        required: true
      TECTON_API_KEY:
        description: 'Tecton API Key for Authentication'
        required: true
  workflow_dispatch:
    branches:
      - 'main'
    inputs:
      client_version:
        description: 'Java Client Version for Testing'
        required: true
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    env:
      TECTON_URL: ${{ secrets.TECTON_URL }} 
      TECTON_API_KEY: ${{ secrets.TECTON_API_KEY }}
      WORKSPACE_NAME: prod_JAVA_CLIENT_TEST_WS_DO_NOT_DELETE
      FEATURE_SERVICE_NAME: fraud_detection_feature_service
      JAVA_CLIENT_VERSION: ${{ inputs.client_version }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8
        cache: gradle
    - name: Log Java Client Version
      run: ./gradlew -q dependencies --configuration compileClasspath 
    - name: Run Tests 
      run: ./gradlew clean test

